### PR TITLE
Support custom domains

### PR DESCRIPTION
**Pull request by skovhus**
Work in progress for fixing #3... I think this PR should do the work, but need to test a bit and understand how the bucket and domain name convention. They seem to be linked in amazon, so a domain foo.com NEEDS to have a bucket foo.com.

What do you do if a bucket name that matches your domain name is taken?

### CODE REVIEW

**Comment by mads-hartmann** [comment]
That sounds funky :) I'll have a look tonight. It's awesome you're working your way through the tickets

**Comment by skovhus** [comment]
> What do you do if a bucket name that matches your domain name is taken?

@mads-hartmann Did you have time to look into this?

**Comment by mads-hartmann** [comment]
Sure thing, I'll take a look, but probably won't be till the weekend :)

**Comment by mads-hartmann** [comment]
@skovhus Can you create a bucket named `tech-conferences.net`? I own that domain so I can test what happens :)

**Comment by skovhus** [comment]
@mads-hartmann the script fails because I don't have a route53 configuration for that domain... But I created a bucket: http://tech-conferences.net.s3-website-us-east-1.amazonaws.com

Which zone are you in?

**Pull request merged**
